version: '3.8'

services:
#  bot:
#    build:
#      context: . # Укажите путь к папке с Dockerfile вашего бота
#    environment:
#      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY} # Укажите переменную окружения для API ключа
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_USER=postgres
#      - DB_PASSWORD=password
#      - DB_NAME=sltest
#    depends_on:
#      - postgres
#    networks:
#      - bot-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sltest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres-data: